In [1]:
import pandas as pd
from scipy.stats import mannwhitneyu
from scipy.stats import spearmanr

In [11]:
data_ex = pd.read_excel('C:/Users/serst/Desktop/Результаты.xlsx', sheet_name = 2, index_col = None)
data_ex.head()

,ex_ind_em,ex_ind_pozn,ex_ind_prakt,ex_ind_postup,ex_ind_intens,ex_ei_opora,ex_ei_zasch,ex_ei_prostr,ex_ei_1fm,ex_ei_sootn,...,ex_ei_cenvb,ex_ei_4fm,ex_ei_ei,ex_vkz_subocz,ex_vkz_cenz,ex_vkz_osvipovk,ex_vkz_lokusk,ex_vkz_pozprog,ex_vkz_sum,ex_addict
0,5,3,5,3,4,8,7,7,22,5,...,7,19,85,39,57,41,46,41,224,19
1,3,2,4,4,3,10,8,9,27,7,...,11,29,110,47,48,40,51,41,227,18
2,5,4,8,5,6,11,7,9,27,8,...,12,34,126,42,51,60,56,46,255,16
3,6,3,3,3,3,12,11,10,33,10,...,12,34,130,62,51,44,52,44,253,14
4,8,8,7,8,8,11,8,7,26,12,...,12,32,128,39,55,42,59,47,242,20

In [52]:
ex_ind_em = list(data_ex.iloc[:, 0])
ex_ind_em

[5,
 3,
 5,
 6,
 8,
 5,
 3,
 4,
 1,
 5,
 7,
 2,
 5,
 3,
 5,
 4,
 5,
 8,
 3,
 3,
 3,
 4,
 6,
 8,
 5,
 5,
 4,
 2,
 3,
 7,
 5,
 1,
 7,
 6,
 2,
 5,
 5,
 5,
 6,
 4,
 3,
 7,
 5,
 8,
 3,
 8,
 7,
 5,
 3,
 5,
 6,
 5,
 7,
 3,
 7,
 6]

In [26]:
variables_ex = list(data_ex.columns.values)
variables_ex

['ex_ind_em',
 'ex_ind_pozn',
 'ex_ind_prakt',
 'ex_ind_postup',
 'ex_ind_intens',
 'ex_ei_opora',
 'ex_ei_zasch',
 'ex_ei_prostr',
 'ex_ei_1fm',
 'ex_ei_sootn',
 'ex_ei_vremia',
 'ex_ei_bliz',
 'ex_ei_2fm',
 'ex_ei_zvnim',
 'ex_ei_sprot',
 'ex_ei_prizc',
 'ex_ei_3fm',
 'ex_ei_vozmdd',
 'ex_ei_vklvv',
 'ex_ei_cenvb',
 'ex_ei_4fm',
 'ex_ei_ei',
 'ex_vkz_subocz',
 'ex_vkz_cenz',
 'ex_vkz_osvipovk',
 'ex_vkz_lokusk',
 'ex_vkz_pozprog',
 'ex_vkz_sum',
 'ex_addict']

In [101]:
variables_list = data_ex.values.T.tolist()
ex_ind_em = variables_list[0]
ex_ind_em

56

In [12]:
data_n_ex = pd.read_excel('C:/Users/serst/Desktop/Результаты.xlsx', sheet_name = 3, index_col = None)
data_n_ex.head()

,n_ex_ind_em,n_ex_ind_pozn,n_ex_ind_prakt,n_ex_ind_postup,n_ex_ind_intens,n_ex_ei_opora,n_ex_ei_zasch,n_ex_ei_prostr,n_ex_ei_1fm,n_ex_ei_sootn,...,n_ex_ei_cenvb,n_ex_ei_4fm,n_ex_ei_ei,n_ex_vkz_subocz,n_ex_vkz_cenz,n_ex_vkz_osvipovk,n_ex_vkz_lokusk,n_ex_vkz_pozprog,n_ex_vkz_sum,n_ex_addict
0,3,4,3,5,4,12,5,9,26,12,...,9,30,120,55,54,39,42,34,224,6
1,3,6,5,6,5,11,11,7,29,10,...,8,29,116,48,46,49,39,40,222,6
2,3,3,3,2,2,12,4,6,22,10,...,10,26,113,42,42,29,46,42,201,6
3,1,4,5,5,4,9,10,5,24,9,...,6,25,106,36,54,40,46,45,221,14
4,5,8,6,8,7,5,8,11,24,11,...,7,21,95,43,38,51,41,40,213,6

In [22]:
variables_n_ex = list(data_n_ex.columns.values)
variables_n_ex

['n_ex_ind_em',
 'n_ex_ind_pozn',
 'n_ex_ind_prakt',
 'n_ex_ind_postup',
 'n_ex_ind_intens',
 'n_ex_ei_opora',
 'n_ex_ei_zasch',
 'n_ex_ei_prostr',
 'n_ex_ei_1fm',
 'n_ex_ei_sootn',
 'n_ex_ei_vremia',
 'n_ex_ei_bliz',
 'n_ex_ei_2fm',
 'n_ex_ei_zvnim',
 'n_ex_ei_sprot',
 'n_ex_ei_prizc',
 'n_ex_ei_3fm',
 'n_ex_ei_vozmdd',
 'n_ex_ei_vklvv',
 'n_ex_ei_cenvb',
 'n_ex_ei_4fm',
 'n_ex_ei_ei',
 'n_ex_vkz_subocz',
 'n_ex_vkz_cenz',
 'n_ex_vkz_osvipovk',
 'n_ex_vkz_lokusk',
 'n_ex_vkz_pozprog',
 'n_ex_vkz_sum',
 'n_ex_addict']