In [2]:
import os
import pandas as pd
import datetime as dtime
import numpy as np
import glob
import zipfile

In [8]:
# Change directory
os.chdir('C:/Users/sstarikov/Documents/Intraday FX risk/ZIP')

In [19]:
# Unzip archives
for zips in List_of_zip:
    unfold_zip = zipfile.ZipFile(zips)
    unfold_zip.extractall()
    os.rename('trades.csv', 'trades' + zips[26:34] + '.csv')
    unfold_zip.close()

In [6]:
# Drop unnecessary columns
os.chdir('C:/Users/sstarikov/Documents/Intraday FX risk/RAW20_2')
trades_appended = pd.DataFrame()
List_of_files = [i for i in glob.glob('*.{}'.format('csv'))]

for files in List_of_files:
    trades = pd.read_csv(files, sep=';', header = 1)
    trades.drop(trades[['INVCURVOL', 'BUYSELL', 'TRADENO']], axis = 1, inplace = True)
    trades_appended = trades_appended.append(trades)
    
trades_appended.to_csv('tradesALL20_2.csv', sep = ';', index = False)

In [12]:
len(trades_appended)

20438402

In [16]:
# Filter
os.chdir('C:/Users/sstarikov/Documents/Intraday FX risk/TRADESALL')
trades = pd.read_csv('tradesALL20_2.csv', sep=';', header = 0)
trades_filter = trades[(trades['TRADETIME'] >= '12:00:00') & (trades['TRADETIME'] <= '16:00:00')
                       & (trades['SECID'] == 'EUR_RUB__TOM') & (trades['BOARDID'] == 'CETS')]
# USD000UTSTOM     EUR_RUB__TOM

In [18]:
trades_filter.to_csv('tradesALL20_2_EUR_12_16.csv', sep = ';', index = False)

In [21]:
# Append all filtered files
os.chdir('C:/Users/sstarikov/Documents/Intraday FX risk/FILTERED/EUR')
trades_appended = pd.DataFrame()
List_of_files = [i for i in glob.glob('*.{}'.format('csv'))]

for files in List_of_files:
    trades = pd.read_csv(files, sep=';', header = 0)
    trades_appended = trades_appended.append(trades)
    
trades_appended.to_csv('tradesALL_EUR_12_16.csv', sep = ';', index = False)

In [31]:
# Derive 12:00 prices
os.chdir('C:/Users/sstarikov/Documents/Intraday FX risk/PREFINAL')
trades = pd.read_csv('tradesALL_EUR_12_16.csv', sep=';', header = 0)
trades_grouped = trades.groupby('TRADEDATE')
first_values = trades_grouped.first()
first_values = first_values.reset_index()
first_values.to_csv('tradesALL_EUR_12.csv', sep = ';', index = False)

    TRADEDATE TRADETIME         SECID BOARDID    PRICE  VOLCUR
0  01.06.2018  12:00:23  EUR_RUB__TOM    CETS   72,655    2000
1  01.06.2018  12:00:50  EUR_RUB__TOM    CETS  72,6625   50000
2  01.06.2018  12:00:50  EUR_RUB__TOM    CETS  72,6625   13000
3  01.06.2018  12:00:50  EUR_RUB__TOM    CETS  72,6625   37000
4  01.06.2018  12:01:58  EUR_RUB__TOM    CETS   72,655    1000

In [49]:
# Derive min intraday prices
os.chdir('C:/Users/sstarikov/Documents/Intraday FX risk/PREFINAL')
trades = pd.read_csv('tradesALL_EUR_12_16.csv', sep = ';', header = 0, decimal = ',')
trades_grouped = trades.groupby('TRADEDATE')
min_values = trades_grouped.min(level = 'PRICE')
min_values = min_values.reset_index()
min_values.head(15)

     TRADEDATE TRADETIME         SECID BOARDID    PRICE  VOLCUR
0   01.02.2019  12:00:04  EUR_RUB__TOM    CETS  74.9550    1000
1   01.02.2021  12:00:06  EUR_RUB__TOM    CETS  91.2000    1000
2   01.03.2019  12:00:00  EUR_RUB__TOM    CETS  74.7775    1000
3   01.03.2021  12:00:02  EUR_RUB__TOM    CETS  89.2000    1000
4   01.04.2019  12:00:00  EUR_RUB__TOM    CETS  73.4400    1000
5   01.04.2020  12:00:39  EUR_RUB__TOM    CETS  85.9000    1000
6   01.06.2018  12:00:23  EUR_RUB__TOM    CETS  72.4850    1000
7   01.06.2020  12:00:10  EUR_RUB__TOM    CETS  77.2500    1000
8   01.07.2019  12:00:05  EUR_RUB__TOM    CETS  71.3675    1000
9   01.08.2018  12:00:15  EUR_RUB__TOM    CETS  73.1475    1000
10  01.08.2019  12:00:17  EUR_RUB__TOM    CETS  70.3775    1000
11  01.09.2020  12:00:10  EUR_RUB__TOM    CETS  88.0200    1000
12  01.10.2018  12:00:01  EUR_RUB__TOM    CETS  76.0075    1000
13  01.10.2019  12:00:12  EUR_RUB__TOM    CETS  70.8225    1000
14  01.10.2020  12:01:10  EUR_RUB__TOM    CETS  90.5500    1000

In [50]:
min_values.to_csv('tradesALL_EUR_MIN.csv', sep = ';', index = False, decimal = ',')

In [51]:
len(min_values)

704

In [22]:
len(trades_appended)

2141537

In [50]:
trades_filter.head(20)

        TRADEDATE TRADETIME         SECID BOARDID    PRICE  VOLCUR
78456  04.01.2021  12:00:00  EUR_RUB__TOM    CETS     89,9    5000
78457  04.01.2021  12:00:00  EUR_RUB__TOM    CETS     89,9    1000
78458  04.01.2021  12:00:00  EUR_RUB__TOM    CETS     89,9    8000
78459  04.01.2021  12:00:00  EUR_RUB__TOM    CETS     89,9    1000
78460  04.01.2021  12:00:00  EUR_RUB__TOM    CETS     89,9   50000
78501  04.01.2021  12:00:02  EUR_RUB__TOM    CETS     89,9    1000
78556  04.01.2021  12:00:04  EUR_RUB__TOM    CETS   89,875    3000
78561  04.01.2021  12:00:04  EUR_RUB__TOM    CETS  89,8725   50000
78660  04.01.2021  12:00:11  EUR_RUB__TOM    CETS  89,8575    1000
78670  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85   10000
78671  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85   40000
78672  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85   10000
78673  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85   50000
78677  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85   50000
78678  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85    1000
78680  04.01.2021  12:00:11  EUR_RUB__TOM    CETS    89,85   50000
78693  04.01.2021  12:00:12  EUR_RUB__TOM    CETS   89,855   13000
78926  04.01.2021  12:00:30  EUR_RUB__TOM    CETS   89,835    1000
78940  04.01.2021  12:00:30  EUR_RUB__TOM    CETS    89,82   50000
78949  04.01.2021  12:00:31  EUR_RUB__TOM    CETS  89,8125    1000